org: gaboooo
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  timeout: 30  
  iam:
    role: arn:aws:iam::044477782735:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarAlumnos.lambda_handler
    events: 
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          lambda: lambda
  eliminar:
    handler: EliminarAlumnos.lambda_handler
    events: 
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          lambda: lambda 
  buscar:
    handler: BuscarAlumnos.lambda_handler
    events: 
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          lambda: lambda
